apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-dify-api-sa
  namespace: dev-dify

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-dify-worker-sa
  namespace: dev-dify

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-dify-worker-beat-sa
  namespace: dev-dify

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-dify-sandbox-sa
  namespace: dev-dify

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-dify-enterprise-api-sa
  namespace: dev-dify

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-dify-enterprise-web-sa
  namespace: dev-dify

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-dify-ssrf-proxy-sa
  namespace: dev-dify

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-dify-unstructured-sa
  namespace: dev-dify
