repository: registry.dev-dify.ctc.local/dev/database/percona-distribution-postgresql:17.7
image: registry.dev-dify.ctc.local/dev/database/percona-distribution-postgresql:17.7
imagePullPolicy: IfNotPresent
postgresVersion: 17

nameOverride: "dev-pg-db"

extraLabels:
  app.kubernetes.io/role: database
  app.kubernetes.io/project: redis-qdrant
  app.kubernetes.io/environment: dev

metadata:
  labels:
    app.kubernetes.io/role: database
    app.kubernetes.io/version: 2.8.0
    app.kubernetes.io/project: redis-qdrant
    app.kubernetes.io/environment: dev

users:
  - name: admin
    grantPublicSchemaAccess: true
    options: "SUPERUSER"
    password:
      type: ASCII
    secretName: pg-admin-secret

  - name: user
    grantPublicSchemaAccess: true
    options: "SUPERUSER"
    password:
      type: ASCII
    secretName: pg-user-secret

instances:
- name: instance1
  replicas: 3

  tolerations:
    - key: "nodepool"
      operator: "Equal"
      value: "dev-data"
      effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "nodepool"
                operator: "In"
                values:
                  - "dev-data"
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: "app.kubernetes.io/component"
                  operator: "In"
                  values:
                    - pg
            topologyKey: "kubernetes.io/hostname"
  
  metadata:
    labels:
      app.kubernetes.io/role: database
      app.kubernetes.io/version: 2.8.0
      app.kubernetes.io/project: redis-qdrant
      app.kubernetes.io/environment: dev

  resources:
    requests:
      cpu: 250m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  securityContext:
    runAsUser: 1001
    fsGroup: 1001
    runAsNonRoot: true
  
  dataVolumeClaimSpec:
    storageClassName: "dev-postgres-openebs-sc"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 6Gi
  walVolumeClaimSpec:
    storageClassName: dev-postgres-openebs-sc
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 4Gi

proxy:
  pgBouncer:
    replicas: 3
    image: registry.dev-dify.ctc.local/dev/database/percona-pgbouncer:1.25.0
    
    resources:
      requests:
        cpu: 250m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "nodepool"
                  operator: "In"
                  values:
                    - "dev-data"
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: pgbouncer
            topologyKey: kubernetes.io/hostname
    
    tolerations:
      - key: "nodepool"
        operator: "Equal"
        value: "dev-data"
        effect: "NoSchedule"
    
    securityContext:
      runAsUser: 1001
      fsGroup: 1001
      runAsNonRoot: true
    
backups:
  enabled: true
  pgbackrest:
    image: registry.dev-dify.ctc.local/dev/database/percona-pgbackrest:2.57.0

    metadata:
      labels:
        app.kubernetes.io/role: database
        app.kubernetes.io/version: 2.8.0
        app.kubernetes.io/project: redis-qdrant
        app.kubernetes.io/environment: dev
    
    containers:
      pgbackrest:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      pgbackrestConfig:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
       
    repoHost:
      enabled: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "nodepool"
                    operator: "In"
                    values:
                      - "dev-data"
        
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: pgbackrest
              topologyKey: kubernetes.io/hostname
        
      tolerations:
        - key: "nodepool"
          operator: "Equal"
          value: "dev-data"
          effect: "NoSchedule"
      
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
        runAsNonRoot: true
      
    manual:
      repoName: repo1
      options:
      - --type=full

    repos:
      - name: repo1
        schedules:
          full: "0 0 * * 0"
          incremental: "0 1 * * 1-6"
        volume:
          volumeClaimSpec:
            storageClassName: dev-postgres-openebs-sc
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
      
      - name: repo2
        schedules:
          full: "0 0 * * 0"
          incremental: "0 3 * * 1-6"
        s3:
          bucket: pgbackrest-bucket
          endpoint: minio.dev-dify.ctc.local:9000
          region: us-east-1
          accessKey: 1yUePlkzozjqqyd8cklp
          secretKey: NejP8h3IZkNGn3WFqZwecLSIElZ3leyOpIWI2AzT

pmm:
  enabled: false
