apiVersion: v1
kind: Endpoints
metadata:
  name: bind-metrics
  namespace: dev-monitoring
subsets:
  - addresses:
      - ip: bind-master.dev-dify.ctc.local
    ports:
      - name: http-metrics
        port: 9119

---

apiVersion: v1
kind: Service
metadata:
  name: bind-metrics
  namespace: dev-monitoring
  labels:
    app: bind
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9119
      targetPort: 9119

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bind-metrics
  namespace: dev-monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - dev-monitoring
  selector:
    matchLabels:
      app: bind
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
      