apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dev-qdrant-openebs-sc
parameters:
  storage: lvm
  volgroup: lvm-openebs
provisioner: local.csi.openebs.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer